#!/bin/bash
$BASEDIR/dev/gcc.sh
$BASEDIR/dev/git.sh
$BASEDIR/dev/python.sh
$BASEDIR/dev/php.sh
$BASEDIR/dev/go.sh
$BASEDIR/dev/ruby.sh
$BASEDIR/dev/java.sh
$BASEDIR/dev/javascript.sh
$BASEDIR/dev/docker.sh
$BASEDIR/dev/mysql.sh
